main/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("post.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("posts/", views.get_all_posts, name="posts"),
    path("posts/<int:pk>/", views.detail_post, name="detail_post"),
    path("posts/create/", views.create_post, name="create_post"),
]

author/models.py
from django.db import models


class Author(models.Model):
    full_name = models.CharField(max_length=150)
    info = models.TextField()
    image = models.ImageField(upload_to="authors")
    created_at = models.DateTimeField(auto_now_add=True)

post/models.py
from django.db import models

from author.models import Author


class Post(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)


class Image(models.Model):
    title = models.CharField(max_length=150)
    image = models.ImageField(upload_to="posts")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='images')


class HashTag(models.Model):
    title = models.CharField(max_length=150)
    post = models.ManyToManyField(Post)

post/forms.py
from django import forms


class PostForm(forms.Form):
    title = forms.CharField(max_length=150, min_length=1)
    description = forms.CharField()
    author = forms.IntegerField()

author/views.py
from django.shortcuts import render

# Create your views here.

post/views.py
from django.shortcuts import render, get_object_or_404, redirect

from author.models import Author
from .forms import PostForm
from .models import Post


def get_all_posts(request):
    posts = Post.objects.all()
    return render(request, "post/posts.html", locals())


def detail_post(request, pk):
    post = get_object_or_404(Post, id=pk)
    return render(request, "post/detail.html", locals())


def create_post(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        data = form.cleaned_data
        author = get_object_or_404(Author, id=data.get("author"))
        Post.objects.create(title=data.get("title"),
                            description=data.get("description"),
                            author=author)
        return redirect("posts")
    return render(request, "post/create.html", locals())

templates/post/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>create</title>
</head>
<body>
<form method="post">
    {%csrf_token%}
{{form.as_p}}
    <input type="submit" value="create">
</form>

</body>
</html>

templates/post/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>detail</title>
</head>
<body>
<h1>{{post.title}}</h1>
<h4>
     {% for hash in post.hashtag_set.all%}
        {{hash.title}}
      {%endfor%}
  </h4>
<p>{{post.description}}</p>
{%for i in post.images.all%}
<img src="{{i.image.url}}" height="100px" width="100px" alt="{{i.image.title}}">
{%endfor%}
<h6>{{post.created_date}}</h6>
<h6>{{post.updated_date}}</h6>
<p>@{{post.author.full_name}}</p>

</body>
</html>

templates/post/posts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
<table class="table">
  <thead class="table-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Автор</th>
      <th scope="col">Посты</th>
      <th scope="col">Описание постов</th>
      <th scope="col">Хештеги</th>
      <th scope="col">Изображение</th>
      <th scope="col">Переход</th>
    </tr>
  </thead>
  <tbody>
  {% for post in posts%}
    <tr>
      <th scope="row">{{post.id}}</th>
      <td>{{post.author.full_name}}</td>
      <td><a href="{% url 'detail_post' post.id %}">{{post.title}}</td>
      <td>{{post.description|truncatechars:50}}</td>

      <td>
        {% for hash in post.hashtag_set.all%}
        {{hash.title}}
      {%endfor%}
      </td>
      <td><img src="{{post.images.first.image.url}}" height="100px" width="100px" alt="{{post.images.first.title}}"></td>
      <td><a href="{% url 'detail_post' post.id %}" class="btn btn-primary">Перейти</a></td>
    </tr>
  {%endfor%}
  </tbody>
</table>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
</body>
</html>